### ISSUE TITLE
cgroup file not found error

### ISSUE THREAD

**Issue by LedgeDash** [princeton-sns/firecracker-tools#10]
```bash
[davidliu@sns59] ./target/debug/firerunner --kernel ../images/vmlinux --rootfs ../images/node-base-console.ext4
thread 'main' panicked at 'Adding child to Cgroup: Error { kind: WriteFailed, cause: Some(Os { code: 2, kind: NotFound, message: "No such file or directory" }) }', src/libcore/result.rs:999:5
```
Fixed with `sudo mkdir /sys/fs/cgroup/cpu/firecracker`.

Should either document or check existence of this file before adding child vm.

**Comment by alevy** [comment]
https://github.com/princeton-sns/firecracker-tools/blob/master/firerunner/bins/controller/README.md#cgroups

**Comment by alevy** [comment]
I guess this should move to a higher up readme since it affects both firerunner and the controller

**Comment by LedgeDash** [comment]
README updated
