### ISSUE TITLE
Command-line option to include/exclude console from rootfs

### ISSUE THREAD

**Issue by alevy** [princeton-sns/firecracker-tools#3]
Add a command line option to the `mk_rootfs.sh` script that excludes/includes the console from being initialized by OpenRC.

Default should be no console, with a command line option to include it, e.g.:

```bash
$ ./mk_rootfs.sh —include-console python2 myrootfs.ext4
```

**Comment by LedgeDash** [comment]
with the --debug option, isn't this issued resolved?

**Comment by alevy** [comment]
Yes
